apiVersion: v1
kind : ServiceAccount
metadata:
  name: flink
  namespace: rx-vigilance
  labels:
    app.kubernetes.io/part-of: rx-vigilance
  annotations:
    iam.gke.io/gcp-service-account: rx-vigilance-sa@vigilancerx-502702.iam.gserviceaccount.com
