apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flink-serviceaccount.yaml
  - flink-rbac.yaml
  - flink-deployment.yaml
  - secret-store.yaml
  - external-secrets.yaml
configurations:
  - imagetransformer.yaml
images:
  - name: ghcr.io/sourabhagari/rx-vigilance
    newTag: 3018388a06419d80153d282f25abb6dec17c898e
