apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flink-serviceaccount.yaml
  - flink-rbac.yaml
  - flink-deployment.yaml
configurations:
  - imagetransformer.yaml
images:
  - name: ghcr.io/sourabhagari/rx-vigilance
    newTag: 188c50f1c4923777e0c60013bd22557e995d2d8c
