apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flink-serviceaccount.yaml
  - flink-rbac.yaml
  - flink-deployment.yaml
  - secret-store.yaml
  - external-secrets.yaml
configurations:
  - imagetransformer.yaml
images:
  - name: ghcr.io/sourabhagari/rx-vigilance
    newTag: 7ba7dfba91a12ca83db9a76121eba37d97de3ea5
